export default {
  Project: '/api/project',
  ProjectOper: '/api/project/:id',
  ProjectUrl: '/api/project/:id/url',
  ProjectEnvOper: '/api/project/:project/env/:id?',
  ProjectUrlGroup: '/api/project/:project/urlgroup/:id?',
  CheckUsernameExist: '/api/user/username/check',
  Article: '/api/article/:id?',
  ArticleComment: '/api/article/:article/comment',
  User: '/api/user',
  SignIn: '/api/user/signin',
  SignUp: '/api/user/signup',
  SendEmailCode: '/api/email/signup',
  UrlGroup: '/api/urlgroup',
  UrlGroupOper: '/api/urlgroup/:id',
  EditUrl: '/api/urlgroup/:urlGroup/url/:id',
};
